# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('category_name', models.CharField(max_length=100, verbose_name='商品分类名')),
            ],
            options={
                'verbose_name': '商品分类管理',
                'verbose_name_plural': '商品分类管理',
                'db_table': '商品分类表',
            },
        ),
        migrations.CreateModel(
            name='GalleryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('img_url', models.ImageField(upload_to='goods_gallery/%Y/%m/%d', verbose_name='商品相册')),
            ],
            options={
                'verbose_name': '商品相册管理',
                'verbose_name_plural': '商品相册管理',
                'db_table': '商品相册表',
            },
        ),
        migrations.CreateModel(
            name='GoodsSKUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('sku_name', models.CharField(max_length=100, verbose_name='SKU商品名')),
                ('introduction', models.CharField(max_length=200, verbose_name='简介')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='单价')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('sales', models.IntegerField(default=0, verbose_name='销量')),
                ('LOGO', models.ImageField(upload_to='goods/%Y/%m/d', verbose_name='封面地址')),
                ('is_sale', models.BooleanField(choices=[(True, '上架'), (False, '下架')], default=False, verbose_name='是否上架')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.CategoryModel', verbose_name='类别')),
            ],
            options={
                'verbose_name': 'SKU商品管理',
                'verbose_name_plural': 'SKU商品管理',
                'db_table': 'SKU商品表',
            },
        ),
        migrations.CreateModel(
            name='GoodsSPUModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('spu_name', models.CharField(max_length=100, verbose_name='SPU名')),
                ('spu_detail', models.TextField(verbose_name='详情')),
            ],
            options={
                'verbose_name': 'SPU商品管理',
                'verbose_name_plural': 'SPU商品管理',
                'db_table': 'SPU商品表',
            },
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('unit_name', models.CharField(max_length=10, verbose_name='单位')),
            ],
            options={
                'verbose_name': '单位管理',
                'verbose_name_plural': '单位管理',
                'db_table': '单位表',
            },
        ),
        migrations.AddField(
            model_name='goodsskumodel',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSPUModel', verbose_name='SPU商品名'),
        ),
        migrations.AddField(
            model_name='goodsskumodel',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.UnitModel', verbose_name='单位'),
        ),
        migrations.AddField(
            model_name='gallerymodel',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSKUModel', verbose_name='SKU商品名'),
        ),
    ]
