# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-10 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('name', models.CharField(max_length=50, verbose_name='运输公司')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='运输价格')),
            ],
            options={
                'verbose_name': '运输公司',
                'verbose_name_plural': '运输公司',
                'db_table': '运输公司',
            },
        ),
    ]
