# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190211_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oder',
            options={'verbose_name': '订单基本信息', 'verbose_name_plural': '订单基本信息'},
        ),
        migrations.AlterModelOptions(
            name='ordergoods',
            options={'verbose_name': '订单商品信息', 'verbose_name_plural': '订单商品信息'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': '支付方式', 'verbose_name_plural': '支付方式'},
        ),
        migrations.AddField(
            model_name='oder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
