# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-20 15:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('phone_num', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='请输入有效手机号码', regex='^1[3,9]\\d{9}$')], verbose_name='登录手机号')),
                ('password', models.CharField(max_length=64, verbose_name='登录密码')),
            ],
            options={
                'verbose_name_plural': '用户登录表',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('name', models.CharField(max_length=10, verbose_name='收货人')),
                ('phone_num', models.CharField(max_length=11, verbose_name='联系电话')),
                ('city', models.CharField(max_length=10, verbose_name='省/市')),
                ('proper', models.CharField(max_length=10, verbose_name='区/县')),
                ('brief', models.CharField(max_length=20, verbose_name='详细地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
            ],
            options={
                'verbose_name_plural': '用户收货地址表',
                'db_table': 'useraddress',
            },
        ),
        migrations.CreateModel(
            name='UserBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否注销')),
                ('nickname', models.CharField(blank=True, max_length=8, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[(1, '男'), (2, '女')], default=1, max_length=2, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('school', models.CharField(blank=True, max_length=20, null=True, verbose_name='学校')),
                ('location', models.CharField(blank=True, max_length=20, null=True, verbose_name='住址')),
                ('hometown', models.CharField(blank=True, max_length=20, null=True, verbose_name='籍贯')),
                ('paypassword', models.CharField(blank=True, max_length=64, null=True, verbose_name='支付密码')),
                ('userinfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name_plural': '用户信息表',
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='useraddress',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
