# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190122_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1, max_length=2, verbose_name='性别'),
        ),
    ]
