# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190122_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='head',
            field=models.ImageField(default='default/head/infortx.png', upload_to='head/%Y%m/', verbose_name='头像'),
        ),
    ]
