# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-29 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190124_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '用户地址管理', 'verbose_name_plural': '用户地址管理'},
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='proper',
            new_name='harea',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='hcity',
            field=models.CharField(default=1, max_length=10, verbose_name='省'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='hproper',
            field=models.CharField(default=1, max_length=10, verbose_name='区/县'),
            preserve_default=False,
        ),
    ]
