# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-11 15:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190129_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='phone_num',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', message='手机格式错误！')], verbose_name='联系电话'),
        ),
    ]
